version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my-custom-network

  myapp-main:
    build: .
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - 8080:8080
    networks:
      - my-custom-network
    environment:
      - spring_rabbitmq_host=rabbitmq

#Networks
networks:
  my-custom-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  my-datavolume: