version: '3'
services:

  #MySQL Service
  db:
    build: database
    container_name: db-main-app
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mainapp
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_PASSWORD: dev
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    volumes:
      - my-datavolume:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app-network

  myapp-main:
    build: .
    restart: on-failure
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8080:8080
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  my-datavolume: